app:
    resource: "@AppBundle/Controller/"
    type:     annotation
oneup_uploader:
    resource: .
    type: uploader


elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

#user_registration:
    #path:     admstzef/register
    #defaults: { _controller: AppBundle:Registration:register }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
