app:
    resource: "@AppBundle/Controller/"
    type:     annotation
oneup_uploader:
    resource: .
    type: uploader


elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"
    prefix: /admstzef


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /users

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /users/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /users/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /users/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /users/profile
