# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\CmsStzefUsers: bcrypt
    access_control:
        #- { path: ^/efconnect, role: ROLE_USER }
        #- { path: ^/elfinder, role: ROLE_USER }
        - { path: ^/admstzef/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admstzef/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admstzef, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            #anonymous: true
            #anonymous: ~ Valor Inicial
            
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
