# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    # keep your service names short
    app.fns:
        class: AppBundle\Utils\Functions
#services:
#    Utils:
#        class: CMSstzef\AppBundle\Utils\Utils\Utilities
